language: c

compiler:
  - clang
  - gcc

install: 
  - sudo apt-get update || true
  - sudo apt-get install build-essential libnuma-dev

script:
  - cd userland; make

notifications:
  email:
    recipients:
      - packager@ntop.org
    on_success: never
    on_failure: always
