/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_demo_2eproto__INCLUDED
#define PROTOBUF_C_demo_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Demo__DEMO Demo__DEMO;


/* --- enums --- */


/* --- messages --- */

struct  _Demo__DEMO
{
  ProtobufCMessage base;
  char *username;
  char *password;
  uint64_t timestamp;
  protobuf_c_boolean has_role;
  int32_t role;
};
#define DEMO__DEMO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&demo__demo__descriptor) \
    , NULL, NULL, 0, 0,0 }


/* Demo__DEMO methods */
void   demo__demo__init
                     (Demo__DEMO         *message);
size_t demo__demo__get_packed_size
                     (const Demo__DEMO   *message);
size_t demo__demo__pack
                     (const Demo__DEMO   *message,
                      uint8_t             *out);
size_t demo__demo__pack_to_buffer
                     (const Demo__DEMO   *message,
                      ProtobufCBuffer     *buffer);
Demo__DEMO *
       demo__demo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   demo__demo__free_unpacked
                     (Demo__DEMO *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Demo__DEMO_Closure)
                 (const Demo__DEMO *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor demo__demo__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_demo_2eproto__INCLUDED */
